User service
karolinak00/projekt-TAB pull request #3
Opened 2022-04-19 18:45 UTC by karolinak00

I have already implemented user service. I'm waitng for your review.

2022-04-25 16:00 UTC, michloj571 requested changes
I'd say it needs work, especially the user service lacks the necessary features

2022-04-25 16:00 UTC, michloj571 commented on backend/src/main/java/pl/polsl/shop/user/UserService.java
>  public class UserService {
What about adding users, clearing user data and so on? Implementing theese functionalities would also require extension of the UserRepository

2022-04-25 16:00 UTC, michloj571 commented on backend/src/main/java/pl/polsl/shop/user/UserException.java
> +public class UserException extends RuntimeException {
If it's the main user exception, I'd suggest to make it an abstract class

2022-04-25 16:00 UTC, michloj571 commented on backend/src/main/java/pl/polsl/shop/user/Address.java
> +public class Address {
I think it should be modelled to an entity and would also require its own table in the database

2022-04-30 12:30 UTC, karolinak00 commented
I have already introduced the changes proposed by you and completed the implementation of the user-service. I'm waiting for your review.

2022-05-23 07:40 UTC, merged